inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_rspec.yml

AllCops:
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'README.md'

Bundler/OrderedGems:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Metrics:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Security:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': ()
    '%i': '[]'
    '%I': '[]'
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': '[]'
    '%x': ()

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma
