version: "3.7"

services:
  api:
    image: iam-rails-api
    build:
      context: .
    entrypoint: sh -c "rm -f tmp/pids/backend.pid && bundle exec rails db:create db:schema:load && bundle exec rails server -p 3000 -b '0.0.0.0' --pid tmp/pids/backend.pid"
    ports:
      - '3000:3000'
    environment:
      POSTGRES_URI: postgres:5432
    volumes:
      - .:/app
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      start_period: 60s
      interval: 30s
      timeout: 5s
      retries: 5

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
