default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'postgres' } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' }%>

development:
  <<: *default
  database: iam-rails_development

test:
  <<: *default
  database: iam-rails_test

production:
  <<: *default
  database: iam-rails_production
